// Tags
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'

// Adverts
export const FETCH_ADVERT_REQUEST = 'FETCH_ADVERT_REQUEST'
export const FETCH_ADVERT_FAILURE = 'FETCH_ADVERT_FAILURE'
export const FETCH_ADVERT_SUCCESS = 'FETCH_ADVERT_SUCCESS'
export const FETCH_ADVERTS_REQUEST = 'FETCH_ADVERTS_REQUEST'
export const FETCH_ADVERTS_FAILURE = 'FETCH_ADVERTS_FAILURE'
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS'
export const EDIT_ADVERT_REQUEST = 'EDIT_ADVERT_REQUEST'
export const EDIT_ADVERT_FAILURE = 'EDIT_ADVERT_FAILURE'
export const EDIT_ADVERT_SUCCESS = 'EDIT_ADVERT_SUCCESS'
export const DELETE_ADVERT_REQUEST = 'DELETE_ADVERT_REQUEST'
export const DELETE_ADVERT_FAILURE = 'DELETE_ADVERT_FAILURE'
export const DELETE_ADVERT_SUCCESS = 'DELETE_ADVERT_SUCCESS'
export const CREATE_ADVERT_REQUEST = 'CREATE_ADVERT_REQUEST'
export const CREATE_ADVERT_FAILURE = 'CREATE_ADVERT_FAILURE'
export const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS'
export const CLEAR_ADVERT = 'CLEAR_ADVERT';

// Navigation
export const SET_FILTERS = 'SET_FILTERS';
export const SET_PAGE = 'SET_PAGE';

// User
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_WITH_TOKEN_FAILURE = 'LOGIN_WITH_TOKEN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_FAVORITE_REQUEST = 'SET_FAVORITE_REQUEST'
export const SET_FAVORITE_FAILURE = 'SET_FAVORITE_FAILURE'
export const SET_FAVORITE_SUCCESS = 'SET_FAVORITE_SUCCESS'