// Fetch data
export const FETCH_USER_CHATS_REQUEST = 'FETCH_USER_CHATS_REQUEST'
export const FETCH_USER_CHATS_FAILURE = 'FETCH_USER_CHATS_FAILURE'
export const FETCH_USER_CHATS_SUCCESS = 'FETCH_USER_CHATS_SUCCESS'
export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST'
export const FETCH_CHAT_FAILURE = 'FETCH_CHAT_FAILURE'
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS'
// Create chat
export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST'
export const CREATE_CHAT_FAILURE = 'CREATE_CHAT_FAILURE'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'