// Related to connect/disconnect
export const SOCKETIO_CONNECT = 'SOCKETIO_CONNECT'
export const SOCKETIO_DISCONNECT = 'SOCKETIO_DISCONNECT'
export const SOCKETIO_CONNECTED_USER = 'SOCKETIO_CONNECTED_USER'
export const SOCKETIO_DISCONNECTED_USER = 'SOCKETIO_DISCONNECTED_USER'
// Related to handle online status
export const SOCKETIO_ALL_ONLINE_USERS = 'SOCKETIO_ALL_ONLINE_USERS'
export const SOCKETIO_ONLINE_USER = 'SOCKETIO_ONLINE_USER'
export const SOCKETIO_OFFLINE_USER = 'SOCKETIO_OFFLINE_USER'
// Related to texting
export const SOCKETIO_IN_MESSAGE = 'SOCKETIO_IN_MESSAGE'
export const SOCKETIO_OUT_MESSAGE = 'SOCKETIO_OUT_MESSAGE'
export const SOCKETIO_OUT_MESSAGE_SENT = 'SOCKETIO_OUT_MESSAGE_SENT'
export const SOCKETIO_OUT_MESSAGES_CONFIRMED = 'SOCKETIO_OUT_MESSAGES_CONFIRMED'