// Actions dispatched by socket io listeners
export const SOCKETIO_CONNECTED = 'SOCKETIO_CONNECTED'
export const SOCKETIO_DISCONNECTED = 'SOCKETIO_DISCONNECTED'
export const SOCKETIO_ONLINE_USER = 'SOCKETIO_ONLINE_USER'
export const SOCKETIO_ALL_ONLINE_USERS = 'SOCKETIO_ALL_ONLINE_USERS'
export const SOCKETIO_OFFLINE_USER = 'SOCKETIO_OFFLINE_USER'
export const SOCKETIO_INCOMING_MESSAGE = 'SOCKETIO_INCOMING_MESSAGE'
export const SOCKETIO_OUTGOING_MESSAGE = 'SOCKETIO_OUTGOING_MESSAGE'